AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: >-
   AWS ElastiCache trigger that retrieves metadata for the KEY.

Parameters: 
  redis_id:
    Type: String
Resources:
  redis:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      CodeUri: .
      Description: 'Read Redis trigger that retrieves metadata for the KEY, implemented in Python 3.7.'
      MemorySize: 256
      Timeout: 5
      Events:
        redis-read:
          Type: Api
          Properties:
            Path: /
            Method: get
      Policies:
      - LambdaInvokePolicy:
          FunctionName: !Ref FunctionNameParameter
        
